###############################################################################
# Created by write_sdc
###############################################################################
current_design riscv_new_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0000 [get_ports {clk}]
create_clock -name spi_clk -period 100.0000 [get_ports {spi_clk}]
set_clock_transition 0.1000 [get_clocks {clk}]
set_clock_transition 0.1000 [get_clocks {spi_clk}]
set_clock_uncertainty 0.1000 clk
set_clock_uncertainty 0.1000 spi_clk
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_read[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_write[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[32]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[33]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[34]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[35]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[36]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[37]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[38]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[39]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[40]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[41]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[42]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[43]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[44]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[45]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[46]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[47]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[48]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[49]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[50]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[51]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[52]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[53]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[54]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[55]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[56]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[57]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[58]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[59]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[60]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[61]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[62]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[63]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {data_read[31]}]
set_load -pin_load 0.0334 [get_ports {data_read[30]}]
set_load -pin_load 0.0334 [get_ports {data_read[29]}]
set_load -pin_load 0.0334 [get_ports {data_read[28]}]
set_load -pin_load 0.0334 [get_ports {data_read[27]}]
set_load -pin_load 0.0334 [get_ports {data_read[26]}]
set_load -pin_load 0.0334 [get_ports {data_read[25]}]
set_load -pin_load 0.0334 [get_ports {data_read[24]}]
set_load -pin_load 0.0334 [get_ports {data_read[23]}]
set_load -pin_load 0.0334 [get_ports {data_read[22]}]
set_load -pin_load 0.0334 [get_ports {data_read[21]}]
set_load -pin_load 0.0334 [get_ports {data_read[20]}]
set_load -pin_load 0.0334 [get_ports {data_read[19]}]
set_load -pin_load 0.0334 [get_ports {data_read[18]}]
set_load -pin_load 0.0334 [get_ports {data_read[17]}]
set_load -pin_load 0.0334 [get_ports {data_read[16]}]
set_load -pin_load 0.0334 [get_ports {data_read[15]}]
set_load -pin_load 0.0334 [get_ports {data_read[14]}]
set_load -pin_load 0.0334 [get_ports {data_read[13]}]
set_load -pin_load 0.0334 [get_ports {data_read[12]}]
set_load -pin_load 0.0334 [get_ports {data_read[11]}]
set_load -pin_load 0.0334 [get_ports {data_read[10]}]
set_load -pin_load 0.0334 [get_ports {data_read[9]}]
set_load -pin_load 0.0334 [get_ports {data_read[8]}]
set_load -pin_load 0.0334 [get_ports {data_read[7]}]
set_load -pin_load 0.0334 [get_ports {data_read[6]}]
set_load -pin_load 0.0334 [get_ports {data_read[5]}]
set_load -pin_load 0.0334 [get_ports {data_read[4]}]
set_load -pin_load 0.0334 [get_ports {data_read[3]}]
set_load -pin_load 0.0334 [get_ports {data_read[2]}]
set_load -pin_load 0.0334 [get_ports {data_read[1]}]
set_load -pin_load 0.0334 [get_ports {data_read[0]}]
set_load -pin_load 0.0334 [get_ports {data_write[31]}]
set_load -pin_load 0.0334 [get_ports {data_write[30]}]
set_load -pin_load 0.0334 [get_ports {data_write[29]}]
set_load -pin_load 0.0334 [get_ports {data_write[28]}]
set_load -pin_load 0.0334 [get_ports {data_write[27]}]
set_load -pin_load 0.0334 [get_ports {data_write[26]}]
set_load -pin_load 0.0334 [get_ports {data_write[25]}]
set_load -pin_load 0.0334 [get_ports {data_write[24]}]
set_load -pin_load 0.0334 [get_ports {data_write[23]}]
set_load -pin_load 0.0334 [get_ports {data_write[22]}]
set_load -pin_load 0.0334 [get_ports {data_write[21]}]
set_load -pin_load 0.0334 [get_ports {data_write[20]}]
set_load -pin_load 0.0334 [get_ports {data_write[19]}]
set_load -pin_load 0.0334 [get_ports {data_write[18]}]
set_load -pin_load 0.0334 [get_ports {data_write[17]}]
set_load -pin_load 0.0334 [get_ports {data_write[16]}]
set_load -pin_load 0.0334 [get_ports {data_write[15]}]
set_load -pin_load 0.0334 [get_ports {data_write[14]}]
set_load -pin_load 0.0334 [get_ports {data_write[13]}]
set_load -pin_load 0.0334 [get_ports {data_write[12]}]
set_load -pin_load 0.0334 [get_ports {data_write[11]}]
set_load -pin_load 0.0334 [get_ports {data_write[10]}]
set_load -pin_load 0.0334 [get_ports {data_write[9]}]
set_load -pin_load 0.0334 [get_ports {data_write[8]}]
set_load -pin_load 0.0334 [get_ports {data_write[7]}]
set_load -pin_load 0.0334 [get_ports {data_write[6]}]
set_load -pin_load 0.0334 [get_ports {data_write[5]}]
set_load -pin_load 0.0334 [get_ports {data_write[4]}]
set_load -pin_load 0.0334 [get_ports {data_write[3]}]
set_load -pin_load 0.0334 [get_ports {data_write[2]}]
set_load -pin_load 0.0334 [get_ports {data_write[1]}]
set_load -pin_load 0.0334 [get_ports {data_write[0]}]
set_load -pin_load 0.0334 [get_ports {instruction[63]}]
set_load -pin_load 0.0334 [get_ports {instruction[62]}]
set_load -pin_load 0.0334 [get_ports {instruction[61]}]
set_load -pin_load 0.0334 [get_ports {instruction[60]}]
set_load -pin_load 0.0334 [get_ports {instruction[59]}]
set_load -pin_load 0.0334 [get_ports {instruction[58]}]
set_load -pin_load 0.0334 [get_ports {instruction[57]}]
set_load -pin_load 0.0334 [get_ports {instruction[56]}]
set_load -pin_load 0.0334 [get_ports {instruction[55]}]
set_load -pin_load 0.0334 [get_ports {instruction[54]}]
set_load -pin_load 0.0334 [get_ports {instruction[53]}]
set_load -pin_load 0.0334 [get_ports {instruction[52]}]
set_load -pin_load 0.0334 [get_ports {instruction[51]}]
set_load -pin_load 0.0334 [get_ports {instruction[50]}]
set_load -pin_load 0.0334 [get_ports {instruction[49]}]
set_load -pin_load 0.0334 [get_ports {instruction[48]}]
set_load -pin_load 0.0334 [get_ports {instruction[47]}]
set_load -pin_load 0.0334 [get_ports {instruction[46]}]
set_load -pin_load 0.0334 [get_ports {instruction[45]}]
set_load -pin_load 0.0334 [get_ports {instruction[44]}]
set_load -pin_load 0.0334 [get_ports {instruction[43]}]
set_load -pin_load 0.0334 [get_ports {instruction[42]}]
set_load -pin_load 0.0334 [get_ports {instruction[41]}]
set_load -pin_load 0.0334 [get_ports {instruction[40]}]
set_load -pin_load 0.0334 [get_ports {instruction[39]}]
set_load -pin_load 0.0334 [get_ports {instruction[38]}]
set_load -pin_load 0.0334 [get_ports {instruction[37]}]
set_load -pin_load 0.0334 [get_ports {instruction[36]}]
set_load -pin_load 0.0334 [get_ports {instruction[35]}]
set_load -pin_load 0.0334 [get_ports {instruction[34]}]
set_load -pin_load 0.0334 [get_ports {instruction[33]}]
set_load -pin_load 0.0334 [get_ports {instruction[32]}]
set_load -pin_load 0.0334 [get_ports {instruction[31]}]
set_load -pin_load 0.0334 [get_ports {instruction[30]}]
set_load -pin_load 0.0334 [get_ports {instruction[29]}]
set_load -pin_load 0.0334 [get_ports {instruction[28]}]
set_load -pin_load 0.0334 [get_ports {instruction[27]}]
set_load -pin_load 0.0334 [get_ports {instruction[26]}]
set_load -pin_load 0.0334 [get_ports {instruction[25]}]
set_load -pin_load 0.0334 [get_ports {instruction[24]}]
set_load -pin_load 0.0334 [get_ports {instruction[23]}]
set_load -pin_load 0.0334 [get_ports {instruction[22]}]
set_load -pin_load 0.0334 [get_ports {instruction[21]}]
set_load -pin_load 0.0334 [get_ports {instruction[20]}]
set_load -pin_load 0.0334 [get_ports {instruction[19]}]
set_load -pin_load 0.0334 [get_ports {instruction[18]}]
set_load -pin_load 0.0334 [get_ports {instruction[17]}]
set_load -pin_load 0.0334 [get_ports {instruction[16]}]
set_load -pin_load 0.0334 [get_ports {instruction[15]}]
set_load -pin_load 0.0334 [get_ports {instruction[14]}]
set_load -pin_load 0.0334 [get_ports {instruction[13]}]
set_load -pin_load 0.0334 [get_ports {instruction[12]}]
set_load -pin_load 0.0334 [get_ports {instruction[11]}]
set_load -pin_load 0.0334 [get_ports {instruction[10]}]
set_load -pin_load 0.0334 [get_ports {instruction[9]}]
set_load -pin_load 0.0334 [get_ports {instruction[8]}]
set_load -pin_load 0.0334 [get_ports {instruction[7]}]
set_load -pin_load 0.0334 [get_ports {instruction[6]}]
set_load -pin_load 0.0334 [get_ports {instruction[5]}]
set_load -pin_load 0.0334 [get_ports {instruction[4]}]
set_load -pin_load 0.0334 [get_ports {instruction[3]}]
set_load -pin_load 0.0334 [get_ports {instruction[2]}]
set_load -pin_load 0.0334 [get_ports {instruction[1]}]
set_load -pin_load 0.0334 [get_ports {instruction[0]}]
set_load -pin_load 0.0334 [get_ports {pc[31]}]
set_load -pin_load 0.0334 [get_ports {pc[30]}]
set_load -pin_load 0.0334 [get_ports {pc[29]}]
set_load -pin_load 0.0334 [get_ports {pc[28]}]
set_load -pin_load 0.0334 [get_ports {pc[27]}]
set_load -pin_load 0.0334 [get_ports {pc[26]}]
set_load -pin_load 0.0334 [get_ports {pc[25]}]
set_load -pin_load 0.0334 [get_ports {pc[24]}]
set_load -pin_load 0.0334 [get_ports {pc[23]}]
set_load -pin_load 0.0334 [get_ports {pc[22]}]
set_load -pin_load 0.0334 [get_ports {pc[21]}]
set_load -pin_load 0.0334 [get_ports {pc[20]}]
set_load -pin_load 0.0334 [get_ports {pc[19]}]
set_load -pin_load 0.0334 [get_ports {pc[18]}]
set_load -pin_load 0.0334 [get_ports {pc[17]}]
set_load -pin_load 0.0334 [get_ports {pc[16]}]
set_load -pin_load 0.0334 [get_ports {pc[15]}]
set_load -pin_load 0.0334 [get_ports {pc[14]}]
set_load -pin_load 0.0334 [get_ports {pc[13]}]
set_load -pin_load 0.0334 [get_ports {pc[12]}]
set_load -pin_load 0.0334 [get_ports {pc[11]}]
set_load -pin_load 0.0334 [get_ports {pc[10]}]
set_load -pin_load 0.0334 [get_ports {pc[9]}]
set_load -pin_load 0.0334 [get_ports {pc[8]}]
set_load -pin_load 0.0334 [get_ports {pc[7]}]
set_load -pin_load 0.0334 [get_ports {pc[6]}]
set_load -pin_load 0.0334 [get_ports {pc[5]}]
set_load -pin_load 0.0334 [get_ports {pc[4]}]
set_load -pin_load 0.0334 [get_ports {pc[3]}]
set_load -pin_load 0.0334 [get_ports {pc[2]}]
set_load -pin_load 0.0334 [get_ports {pc[1]}]
set_load -pin_load 0.0334 [get_ports {pc[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
