/* Generated by Yosys 0.34+27 (git sha1 7d30f716e, clang 10.0.0-4ubuntu1 -fPIC -Os) */
`timescale 1ns / 1ps
module replica_ALU(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  sky130_fd_sc_hd__inv_2 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule
